name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  relase:
    name: Run tests and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun-

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - run: bun install

      - name: Run Tests
        run: bun run test

      - name: Try to build
        run: bun run build
